version: '2'

services:
  postgres:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: evdata
      POSTGRES_USER: evdata
      POSTGRES_PASSWORD: tagtag

  minio:
    image: minio/minio
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: "server /data"
    ports:
      - 9000:9000
    environment:
      MINIO_ACCESS_KEY: "minio_dev"
      MINIO_SECRET_KEY: "tagtagtag"

  ev-data-api:
    build: .
    image: dev.hbbx.de:4300/ev-manager/ev-manager-data-api:latest
    environment:
      SECRET_KEY: "392pfheoap2ho2ufb"
      ENVIRONMENT: "dev"
      DATABASE_URI: "postgresql+psycopg2://evdata:tagtag@db/evdata"
      S3_ACCESS_KEY: "minio_dev"
      S3_SECRET_KEY: "tagtagtag"
      DATA_EFI_STROM_HOST: "http://efidata"
      MINIO_HOST: "minio:9000"
      MINIO_SECURE: "False"
      EMAIL_HOST: "smtp.mailtrap.io"
      EMAIL_PORT: "2525"
      EMAIL_HOST_USER: "4917ba2a999d71"
      EMAIL_HOST_PASSWORD: "916afe6444d771"
      EMAIL_USE_TLS: "True"
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations
    networks:
      - default
      - shared
    ports:
      - 5000:5000
    links:
      - postgres:db
      - minio:s3
    depends_on:
      - postgres
      - minio



volumes:
  postgres_data:
  minio_data:
  minio_config:

networks:
  shared:
    external:
      name: kez_default