"""task persistent users

Revision ID: 03c1a9f64db0
Revises: bb8fc362890f
Create Date: 2021-02-19 10:16:45.180149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '03c1a9f64db0'
down_revision = 'bb8fc362890f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_persistent_users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bitrix_task_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_persistent_users_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('bitrix_task_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_task_persistent_users_version_end_transaction_id'), 'task_persistent_users_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_task_persistent_users_version_operation_type'), 'task_persistent_users_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_task_persistent_users_version_transaction_id'), 'task_persistent_users_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_persistent_users_version')
    op.drop_table('task_persistent_users')
    # ### end Alembic commands ###
