"""power meters added

Revision ID: 04fd932d5455
Revises: 665bbe0b2a51
Create Date: 2020-12-17 10:54:22.246889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04fd932d5455'
down_revision = '665bbe0b2a51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power_meter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('contract_unique_identifier', sa.String(length=80), nullable=True),
    sa.Column('number', sa.String(length=80), nullable=True),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('device_energy_type', sa.String(length=120), nullable=True),
    sa.Column('family_type', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('power_meter_measurement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('power_meter_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('raw', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('power_meter_measurement')
    op.drop_table('power_meter')
    # ### end Alembic commands ###
