"""empty message

Revision ID: 071d5c38c3e6
Revises: 66b03a911254
Create Date: 2023-05-04 14:47:48.223250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '071d5c38c3e6'
down_revision = '66b03a911254'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enbw_contract', sa.Column('enbw_contract_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enbw_contract', 'enbw_contract_number')
    # ### end Alembic commands ###
