"""lead_id for surveys

Revision ID: 0a3e9554c008
Revises: e0fc637ec6bc
Create Date: 2020-03-27 09:16:53.302295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a3e9554c008'
down_revision = 'e0fc637ec6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('lead_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'survey', 'lead', ['lead_id'], ['id'])
    op.add_column('survey_version', sa.Column('lead_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey_version', 'lead_id')
    op.drop_constraint(None, 'survey', type_='foreignkey')
    op.drop_column('survey', 'lead_id')
    # ### end Alembic commands ###
