"""attachments added for lead

Revision ID: 0ad63b00154c
Revises: 7b98d951a246
Create Date: 2019-08-07 19:01:47.166425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad63b00154c'
down_revision = '7b98d951a246'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('attachments', sa.JSON(), nullable=True))
    op.add_column('lead_version', sa.Column('attachments', sa.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_version', 'attachments')
    op.drop_column('lead', 'attachments')
    # ### end Alembic commands ###
