"""empty message

Revision ID: 0bdf556fba4a
Revises: 0cc3c6454e48
Create Date: 2019-10-23 09:14:34.926012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bdf556fba4a'
down_revision = '0cc3c6454e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_action', sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('event_action', 'trigger')
    op.add_column('event_action_version', sa.Column('triggers', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('event_action_version', 'trigger')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_action_version', sa.Column('trigger', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('event_action_version', 'triggers')
    op.add_column('event_action', sa.Column('trigger', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('event_action', 'triggers')
    # ### end Alembic commands ###
