"""user_cache added

Revision ID: 0c5968969963
Revises: 2748ea232b4c
Create Date: 2021-05-26 07:40:00.188735

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0c5968969963'
down_revision = '2748ea232b4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bitrix_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('department', sa.String(length=250), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cache')
    # ### end Alembic commands ###
