"""empty message

Revision ID: 0cc3c6454e48
Revises: 96547aa68240
Create Date: 2019-10-23 08:24:54.790438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cc3c6454e48'
down_revision = '96547aa68240'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('email', sa.Column('template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'email', 'email_template', ['template_id'], ['id'])
    op.create_foreign_key(None, 'email', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.drop_constraint(None, 'email', type_='foreignkey')
    op.drop_column('email', 'template_id')
    # ### end Alembic commands ###
