"""customer

Revision ID: 0ddec445f1f3
Revises: b9065cf0a32a
Create Date: 2019-06-18 10:01:08.980358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ddec445f1f3'
down_revision = 'b9065cf0a32a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'customer', 'customer_address', ['default_address_id'], ['id'])
    op.create_foreign_key(None, 'customer', 'customer_payment_account', ['default_payment_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint(None, 'customer', type_='foreignkey')
    # ### end Alembic commands ###
