"""contract status

Revision ID: 0de7701bfb10
Revises: 2a0ca935bb8b
Create Date: 2022-02-23 14:32:47.624416

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0de7701bfb10'
down_revision = '2a0ca935bb8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_status', sa.Column('has_smartme_number_heatcloud', sa.Boolean(), nullable=True))
    op.add_column('contract_status', sa.Column('has_smartme_number_heatcloud_values', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_status', 'has_smartme_number_heatcloud_values')
    op.drop_column('contract_status', 'has_smartme_number_heatcloud')
    # ### end Alembic commands ###
