"""empty message

Revision ID: 0e88545a5761
Revises: 1610fb0542cc
Create Date: 2019-10-15 08:20:56.678939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e88545a5761'
down_revision = '1610fb0542cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
