"""order with offer_id

Revision ID: 114a3d17f550
Revises: e60af25c82e5
Create Date: 2020-07-29 14:41:07.623517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114a3d17f550'
down_revision = 'e60af25c82e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'offer_v2', ['offer_id'], ['id'])
    op.add_column('order_version', sa.Column('offer_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_version', 'offer_id')
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'offer_id')
    # ### end Alembic commands ###
