"""contracts2

Revision ID: 1155e607f8e4
Revises: c91ba1b2030e
Create Date: 2022-03-03 19:02:37.072694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1155e607f8e4'
down_revision = 'c91ba1b2030e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract2', sa.Column('begin', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract2', 'begin')
    # ### end Alembic commands ###
