"""product packet range

Revision ID: 125092c3ea2f
Revises: bc183f1e7455
Create Date: 2020-04-16 13:19:50.254266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '125092c3ea2f'
down_revision = 'bc183f1e7455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('packet_range_end', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('packet_range_start', sa.Integer(), nullable=True))
    op.add_column('product_version', sa.Column('packet_range_end', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('packet_range_start', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_version', 'packet_range_start')
    op.drop_column('product_version', 'packet_range_end')
    op.drop_column('product', 'packet_range_start')
    op.drop_column('product', 'packet_range_end')
    # ### end Alembic commands ###
