"""product extended

Revision ID: 154eefea79a6
Revises: 0a3e9554c008
Create Date: 2020-03-31 10:52:37.489195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154eefea79a6'
down_revision = '0a3e9554c008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('product_version', sa.Column('description', sa.Text(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_version', 'description')
    op.drop_column('product', 'description')
    # ### end Alembic commands ###
