"""empty message

Revision ID: 1610fb0542cc
Revises: b6a6b5923248
Create Date: 2019-10-15 08:19:38.859375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1610fb0542cc'
down_revision = 'b6a6b5923248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_comments', sa.Column('automated', sa.Boolean(), nullable=True))
    op.add_column('lead_comments', sa.Column('code', sa.String(length=80), nullable=True))
    op.add_column('lead_comments_version', sa.Column('automated', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('lead_comments_version', sa.Column('code', sa.String(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_comments_version', 'code')
    op.drop_column('lead_comments_version', 'automated')
    op.drop_column('lead_comments', 'code')
    op.drop_column('lead_comments', 'automated')
    # ### end Alembic commands ###
