"""lead_activities

Revision ID: 16896bb18c44
Revises: 0ad63b00154c
Create Date: 2019-09-03 13:01:35.057444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16896bb18c44'
down_revision = '0ad63b00154c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_activity_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('action', sa.String(length=80), autoincrement=False, nullable=True),
    sa.Column('action_data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_lead_activity_version_end_transaction_id'), 'lead_activity_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_lead_activity_version_operation_type'), 'lead_activity_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_lead_activity_version_transaction_id'), 'lead_activity_version', ['transaction_id'], unique=False)
    op.create_table('lead_activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=True),
    sa.Column('action_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead_activity')
    op.drop_index(op.f('ix_lead_activity_version_transaction_id'), table_name='lead_activity_version')
    op.drop_index(op.f('ix_lead_activity_version_operation_type'), table_name='lead_activity_version')
    op.drop_index(op.f('ix_lead_activity_version_end_transaction_id'), table_name='lead_activity_version')
    op.drop_table('lead_activity_version')
    # ### end Alembic commands ###
