"""bundle is running

Revision ID: 16cd7b1fceb4
Revises: ff7b2a6133b3
Create Date: 2022-08-08 12:24:41.561218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '16cd7b1fceb4'
down_revision = 'ff7b2a6133b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_bundle', sa.Column('is_running', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_bundle', 'is_running')
    # ### end Alembic commands ###
