"""update status

Revision ID: 23585e506329
Revises: 524e6c5242e2
Create Date: 2019-07-30 14:27:10.279632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23585e506329'
down_revision = '524e6c5242e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_comments', sa.Column('change_to_offer_created', sa.Boolean(), nullable=True))
    op.add_column('lead_comments_version', sa.Column('change_to_offer_created', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_comments_version', 'change_to_offer_created')
    op.drop_column('lead_comments', 'change_to_offer_created')
    # ### end Alembic commands ###
