"""reseller_commission_info

Revision ID: 23a94198b9bf
Revises: 4f45ae29fa8d
Create Date: 2020-01-23 09:21:19.291433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23a94198b9bf'
down_revision = '4f45ae29fa8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reseller', sa.Column('lead_year_target', sa.Integer(), nullable=True))
    op.add_column('reseller', sa.Column('leads_per_month', sa.Integer(), nullable=True))
    op.add_column('reseller', sa.Column('min_commission', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('reseller_version', sa.Column('lead_year_target', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('reseller_version', sa.Column('leads_per_month', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('reseller_version', sa.Column('min_commission', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reseller_version', 'min_commission')
    op.drop_column('reseller_version', 'leads_per_month')
    op.drop_column('reseller_version', 'lead_year_target')
    op.drop_column('reseller', 'min_commission')
    op.drop_column('reseller', 'leads_per_month')
    op.drop_column('reseller', 'lead_year_target')
    # ### end Alembic commands ###
