"""mfr import buffer added

Revision ID: 2748ea232b4c
Revises: 03c1a9f64db0
Create Date: 2021-04-20 13:45:32.622604

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2748ea232b4c'
down_revision = '03c1a9f64db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfr_import_buffer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_request_id', sa.String(length=200), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('mfr_import_buffer')
    # ### end Alembic commands ###
