"""contract status

Revision ID: 2a0ca935bb8b
Revises: a1ab4838fbdb
Create Date: 2022-02-23 14:23:04.600965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2a0ca935bb8b'
down_revision = 'a1ab4838fbdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_status', sa.Column('cloud_number', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_status', 'cloud_number')
    # ### end Alembic commands ###
