"""s3 deleted flag

Revision ID: 37d8b3ab7262
Revises: a84cb0860a11
Create Date: 2022-06-20 08:08:44.587467

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '37d8b3ab7262'
down_revision = 'a84cb0860a11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_file', sa.Column('is_s3_deleted', sa.Boolean(), nullable=True))
    op.add_column('s3_file_version', sa.Column('is_s3_deleted', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s3_file_version', 'is_s3_deleted')
    op.drop_column('s3_file', 'is_s3_deleted')
    # ### end Alembic commands ###
