"""enbw contract2

Revision ID: 382b529695a1
Revises: f8c8e0f7b590
Create Date: 2023-01-24 10:13:39.241774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '382b529695a1'
down_revision = 'f8c8e0f7b590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('enbw_contract', sa.Column('status_message', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enbw_contract', 'status_message')
    # ### end Alembic commands ###
