"""offer item position

Revision ID: 3944b52aa644
Revises: 125092c3ea2f
Create Date: 2020-04-17 09:01:36.036661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3944b52aa644'
down_revision = '125092c3ea2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_v2_items', sa.Column('position', sa.String(length=10), nullable=True))
    op.add_column('offer_v2_items_version', sa.Column('position', sa.String(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer_v2_items_version', 'position')
    op.drop_column('offer_v2_items', 'position')
    # ### end Alembic commands ###
