"""task created_by id added

Revision ID: 3996e7762de6
Revises: a9ddd100091c
Create Date: 2020-05-27 09:27:10.891891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3996e7762de6'
down_revision = 'a9ddd100091c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'created_by_id')
    # ### end Alembic commands ###
