"""cal event extended

Revision ID: 3e19a67ccd5d
Revises: 70d3edb51581
Create Date: 2020-03-11 13:40:56.740903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e19a67ccd5d'
down_revision = '70d3edb51581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_event', 'task', ['task_id'], ['id'])
    op.add_column('calendar_event_version', sa.Column('task_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_version', 'task_id')
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.drop_column('calendar_event', 'task_id')
    # ### end Alembic commands ###
