"""base models added

Revision ID: 42902f374e11
Revises: c127d4fcd42f
Create Date: 2019-07-02 14:53:12.103005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42902f374e11'
down_revision = 'c127d4fcd42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reseller_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('price_definition', sa.JSON(), nullable=True),
    sa.Column('products', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reseller_group_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('price_definition', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('products', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_reseller_group_version_end_transaction_id'), 'reseller_group_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_reseller_group_version_operation_type'), 'reseller_group_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_reseller_group_version_transaction_id'), 'reseller_group_version', ['transaction_id'], unique=False)
    op.create_table('reseller',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('number', sa.String(length=120), nullable=True),
    sa.Column('access_key', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['reseller_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reseller_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('number', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('access_key', sa.String(length=60), autoincrement=False, nullable=True),
    sa.Column('phone', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_reseller_version_end_transaction_id'), 'reseller_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_reseller_version_operation_type'), 'reseller_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_reseller_version_transaction_id'), 'reseller_version', ['transaction_id'], unique=False)
    op.create_table('contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['customer_payment_account.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('payment_account_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_contract_version_end_transaction_id'), 'contract_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_contract_version_operation_type'), 'contract_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_contract_version_transaction_id'), 'contract_version', ['transaction_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_product_version_end_transaction_id'), 'product_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_product_version_operation_type'), 'product_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_product_version_transaction_id'), 'product_version', ['transaction_id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['customer_payment_account.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('payment_account_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_project_version_end_transaction_id'), 'project_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_project_version_operation_type'), 'project_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_project_version_transaction_id'), 'project_version', ['transaction_id'], unique=False)
    op.create_table('offer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('calculation', sa.JSON(), nullable=True),
    sa.Column('price_definition', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['customer_payment_account.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('payment_account_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('calculation', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('price_definition', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('errors', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_offer_version_end_transaction_id'), 'offer_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_offer_version_operation_type'), 'offer_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_offer_version_transaction_id'), 'offer_version', ['transaction_id'], unique=False)
    op.create_table('pv_system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pv_system_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_pv_system_version_end_transaction_id'), 'pv_system_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_pv_system_version_operation_type'), 'pv_system_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_pv_system_version_transaction_id'), 'pv_system_version', ['transaction_id'], unique=False)
    op.create_table('survey',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('offer_until', sa.Date(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('offer_until', sa.Date(), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_survey_version_end_transaction_id'), 'survey_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_survey_version_operation_type'), 'survey_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_survey_version_transaction_id'), 'survey_version', ['transaction_id'], unique=False)
    op.add_column('task', sa.Column('contract_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('pv_system_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('reseller_id', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
    op.create_foreign_key(None, 'task', 'offer', ['offer_id'], ['id'])
    op.create_foreign_key(None, 'task', 'contract', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'task', 'survey', ['survey_id'], ['id'])
    op.create_foreign_key(None, 'task', 'pv_system', ['pv_system_id'], ['id'])
    op.create_foreign_key(None, 'task', 'product', ['product_id'], ['id'])
    op.create_foreign_key(None, 'task', 'reseller', ['reseller_id'], ['id'])
    op.add_column('task_version', sa.Column('contract_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('offer_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('product_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('pv_system_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('survey_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_version', 'survey_id')
    op.drop_column('task_version', 'reseller_id')
    op.drop_column('task_version', 'pv_system_id')
    op.drop_column('task_version', 'project_id')
    op.drop_column('task_version', 'product_id')
    op.drop_column('task_version', 'offer_id')
    op.drop_column('task_version', 'contract_id')
    op.drop_column('task', 'survey_id')
    op.drop_column('task', 'reseller_id')
    op.drop_column('task', 'pv_system_id')
    op.drop_column('task', 'project_id')
    op.drop_column('task', 'product_id')
    op.drop_column('task', 'offer_id')
    op.drop_column('task', 'contract_id')
    op.drop_index(op.f('ix_survey_version_transaction_id'), table_name='survey_version')
    op.drop_index(op.f('ix_survey_version_operation_type'), table_name='survey_version')
    op.drop_index(op.f('ix_survey_version_end_transaction_id'), table_name='survey_version')
    op.drop_table('survey_version')
    op.drop_table('survey')
    op.drop_index(op.f('ix_pv_system_version_transaction_id'), table_name='pv_system_version')
    op.drop_index(op.f('ix_pv_system_version_operation_type'), table_name='pv_system_version')
    op.drop_index(op.f('ix_pv_system_version_end_transaction_id'), table_name='pv_system_version')
    op.drop_table('pv_system_version')
    op.drop_table('pv_system')
    op.drop_index(op.f('ix_project_version_transaction_id'), table_name='project_version')
    op.drop_index(op.f('ix_project_version_operation_type'), table_name='project_version')
    op.drop_index(op.f('ix_project_version_end_transaction_id'), table_name='project_version')
    op.drop_table('project_version')
    op.drop_table('project')
    op.drop_index(op.f('ix_offer_version_transaction_id'), table_name='offer_version')
    op.drop_index(op.f('ix_offer_version_operation_type'), table_name='offer_version')
    op.drop_index(op.f('ix_offer_version_end_transaction_id'), table_name='offer_version')
    op.drop_table('offer_version')
    op.drop_table('offer')
    op.drop_index(op.f('ix_contract_version_transaction_id'), table_name='contract_version')
    op.drop_index(op.f('ix_contract_version_operation_type'), table_name='contract_version')
    op.drop_index(op.f('ix_contract_version_end_transaction_id'), table_name='contract_version')
    op.drop_table('contract_version')
    op.drop_table('contract')
    op.drop_index(op.f('ix_reseller_version_transaction_id'), table_name='reseller_version')
    op.drop_index(op.f('ix_reseller_version_operation_type'), table_name='reseller_version')
    op.drop_index(op.f('ix_reseller_version_end_transaction_id'), table_name='reseller_version')
    op.drop_index(op.f('ix_product_version_transaction_id'), table_name='product_version')
    op.drop_index(op.f('ix_product_version_operation_type'), table_name='product_version')
    op.drop_index(op.f('ix_product_version_end_transaction_id'), table_name='product_version')
    op.drop_table('product_version')
    op.drop_table('product')
    op.drop_table('reseller_version')
    op.drop_table('reseller')
    op.drop_index(op.f('ix_reseller_group_version_transaction_id'), table_name='reseller_group_version')
    op.drop_index(op.f('ix_reseller_group_version_operation_type'), table_name='reseller_group_version')
    op.drop_index(op.f('ix_reseller_group_version_end_transaction_id'), table_name='reseller_group_version')
    op.drop_table('reseller_group_version')
    op.drop_table('reseller_group')
    # ### end Alembic commands ###
