"""order extended

Revision ID: 45adc391573b
Revises: e2b58d7a182f
Create Date: 2020-03-10 10:46:36.462530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45adc391573b'
down_revision = 'e2b58d7a182f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('category', sa.String(length=80), nullable=True))
    op.add_column('order', sa.Column('type', sa.String(length=60), nullable=True))
    op.add_column('order_version', sa.Column('category', sa.String(length=80), autoincrement=False, nullable=True))
    op.add_column('order_version', sa.Column('type', sa.String(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_version', 'type')
    op.drop_column('order_version', 'category')
    op.drop_column('order', 'type')
    op.drop_column('order', 'category')
    # ### end Alembic commands ###
