"""to pay

Revision ID: 4c768a1f9fbf
Revises: ed2bd55b7afb
Create Date: 2022-03-02 16:36:38.320982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c768a1f9fbf'
down_revision = 'ed2bd55b7afb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_status', sa.Column('to_pay', sa.Numeric(precision=12, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_status', 'to_pay')
    # ### end Alembic commands ###
