"""empty message

Revision ID: 4f272d3eb7d5
Revises: 0e88545a5761
Create Date: 2019-10-17 08:41:45.776404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f272d3eb7d5'
down_revision = '0e88545a5761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('contact_source', sa.String(length=80), nullable=True))
    op.add_column('lead_version', sa.Column('contact_source', sa.String(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_version', 'contact_source')
    op.drop_column('lead', 'contact_source')
    # ### end Alembic commands ###
