"""commission requirements

Revision ID: 4f45ae29fa8d
Revises: 83202e2bc770
Create Date: 2020-01-22 13:33:23.356811

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f45ae29fa8d'
down_revision = '83202e2bc770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('commissions', sa.JSON(), nullable=True))
    op.drop_column('lead', 'commission_net')
    op.drop_column('lead', 'commission_rate')
    op.drop_column('lead', 'discount_range')
    op.drop_column('lead', 'final_price_net')
    op.drop_column('lead', 'sold_options')
    op.add_column('lead_version', sa.Column('commissions', sa.JSON(), autoincrement=False, nullable=True))
    op.drop_column('lead_version', 'commission_net')
    op.drop_column('lead_version', 'commission_rate')
    op.drop_column('lead_version', 'discount_range')
    op.drop_column('lead_version', 'final_price_net')
    op.drop_column('lead_version', 'sold_options')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_version', sa.Column('sold_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('lead_version', sa.Column('final_price_net', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('lead_version', sa.Column('discount_range', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('lead_version', sa.Column('commission_rate', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('lead_version', sa.Column('commission_net', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.drop_column('lead_version', 'commissions')
    op.add_column('lead', sa.Column('sold_options', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('final_price_net', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('discount_range', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('commission_rate', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('lead', sa.Column('commission_net', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.drop_column('lead', 'commissions')
    # ### end Alembic commands ###
