"""events

Revision ID: 50b680cef49b
Revises: a42441cb8e7d
Create Date: 2019-10-22 10:33:45.139671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50b680cef49b'
down_revision = 'a42441cb8e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_action_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('trigger', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('action', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('ordering', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('config', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_event_action_version_end_transaction_id'), 'event_action_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_event_action_version_operation_type'), 'event_action_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_event_action_version_transaction_id'), 'event_action_version', ['transaction_id'], unique=False)
    op.create_table('event_trigger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_trigger_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('name', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('error', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_event_trigger_version_end_transaction_id'), 'event_trigger_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_event_trigger_version_operation_type'), 'event_trigger_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_event_trigger_version_transaction_id'), 'event_trigger_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_trigger_version_transaction_id'), table_name='event_trigger_version')
    op.drop_index(op.f('ix_event_trigger_version_operation_type'), table_name='event_trigger_version')
    op.drop_index(op.f('ix_event_trigger_version_end_transaction_id'), table_name='event_trigger_version')
    op.drop_table('event_trigger_version')
    op.drop_table('event_trigger')
    op.drop_index(op.f('ix_event_action_version_transaction_id'), table_name='event_action_version')
    op.drop_index(op.f('ix_event_action_version_operation_type'), table_name='event_action_version')
    op.drop_index(op.f('ix_event_action_version_end_transaction_id'), table_name='event_action_version')
    op.drop_table('event_action_version')
    op.drop_table('event_action')
    # ### end Alembic commands ###
