"""datetimes added to lead and lead comments

Revision ID: 524e6c5242e2
Revises: ad5ec78193e3
Create Date: 2019-07-25 13:12:10.374731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524e6c5242e2'
down_revision = 'ad5ec78193e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_comments_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('lead_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachments', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_lead_comments_version_end_transaction_id'), 'lead_comments_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_lead_comments_version_operation_type'), 'lead_comments_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_lead_comments_version_transaction_id'), 'lead_comments_version', ['transaction_id'], unique=False)
    op.create_table('lead_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lead', sa.Column('datetime', sa.DateTime(), nullable=True))
    op.add_column('lead', sa.Column('reminder_datetime', sa.DateTime(), nullable=True))
    op.add_column('lead_version', sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('lead_version', sa.Column('reminder_datetime', sa.DateTime(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_version', 'reminder_datetime')
    op.drop_column('lead_version', 'datetime')
    op.drop_column('lead', 'reminder_datetime')
    op.drop_column('lead', 'datetime')
    op.drop_table('lead_comments')
    op.drop_index(op.f('ix_lead_comments_version_transaction_id'), table_name='lead_comments_version')
    op.drop_index(op.f('ix_lead_comments_version_operation_type'), table_name='lead_comments_version')
    op.drop_index(op.f('ix_lead_comments_version_end_transaction_id'), table_name='lead_comments_version')
    op.drop_table('lead_comments_version')
    # ### end Alembic commands ###
