"""lead model added

Revision ID: 56fa093c6c89
Revises: 674f8ccc4fe8
Create Date: 2019-07-17 13:57:40.085950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fa093c6c89'
down_revision = '674f8ccc4fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('number', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_lead_version_end_transaction_id'), 'lead_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_lead_version_operation_type'), 'lead_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_lead_version_transaction_id'), 'lead_version', ['transaction_id'], unique=False)
    op.create_table('lead',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    op.drop_index(op.f('ix_lead_version_transaction_id'), table_name='lead_version')
    op.drop_index(op.f('ix_lead_version_operation_type'), table_name='lead_version')
    op.drop_index(op.f('ix_lead_version_end_transaction_id'), table_name='lead_version')
    op.drop_table('lead_version')
    # ### end Alembic commands ###
