"""user direct access key

Revision ID: 5eb7aac2777c
Revises: 3996e7762de6
Create Date: 2020-06-10 07:59:41.027240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eb7aac2777c'
down_revision = '3996e7762de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_key', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_key')
    # ### end Alembic commands ###
