"""empty message

Revision ID: 66b03a911254
Revises: 80b109f7b676
Create Date: 2023-04-24 11:26:11.571037

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '66b03a911254'
down_revision = '80b109f7b676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enbw_contract', sa.Column('tarif_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('enbw_contract', 'tarif_data')
    # ### end Alembic commands ###