"""empty message

Revision ID: 66fd4271fac1
Revises: 50b680cef49b
Create Date: 2019-10-22 10:42:10.615239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fd4271fac1'
down_revision = '50b680cef49b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_trigger', sa.Column('status', sa.String(length=30), nullable=True))
    op.add_column('event_trigger_version', sa.Column('status', sa.String(length=30), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_trigger_version', 'status')
    op.drop_column('event_trigger', 'status')
    # ### end Alembic commands ###
