"""user_id added tasks and reseller

Revision ID: 67a816f5c8cf
Revises: da1926f33f28
Create Date: 2019-07-03 15:10:38.057091

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67a816f5c8cf'
down_revision = 'da1926f33f28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reseller', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reseller', 'user', ['user_id'], ['id'])
    op.add_column('task', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'user_id')
    op.drop_constraint(None, 'reseller', type_='foreignkey')
    op.drop_column('reseller', 'user_id')
    # ### end Alembic commands ###
