"""department chache

Revision ID: 67fba8668bc7
Revises: 04fd932d5455
Create Date: 2021-01-13 13:29:11.684774

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67fba8668bc7'
down_revision = '04fd932d5455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitrix_department',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bitrix_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bitrix_department_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('bitrix_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_bitrix_department_version_end_transaction_id'), 'bitrix_department_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_bitrix_department_version_operation_type'), 'bitrix_department_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_bitrix_department_version_transaction_id'), 'bitrix_department_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bitrix_department_version_transaction_id'), table_name='bitrix_department_version')
    op.drop_index(op.f('ix_bitrix_department_version_operation_type'), table_name='bitrix_department_version')
    op.drop_index(op.f('ix_bitrix_department_version_end_transaction_id'), table_name='bitrix_department_version')
    op.drop_table('bitrix_department_version')
    op.drop_table('bitrix_department')
    # ### end Alembic commands ###
