"""file model added

Revision ID: 75ca5295cbb0
Revises: 56fa093c6c89
Create Date: 2019-07-17 15:57:12.954449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75ca5295cbb0'
down_revision = '56fa093c6c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3_file',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('uploaded', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('s3_file_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('uuid', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=True),
    sa.Column('model', sa.String(length=80), autoincrement=False, nullable=True),
    sa.Column('model_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('uploaded', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_s3_file_version_end_transaction_id'), 's3_file_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_s3_file_version_operation_type'), 's3_file_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_s3_file_version_transaction_id'), 's3_file_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_s3_file_version_transaction_id'), table_name='s3_file_version')
    op.drop_index(op.f('ix_s3_file_version_operation_type'), table_name='s3_file_version')
    op.drop_index(op.f('ix_s3_file_version_end_transaction_id'), table_name='s3_file_version')
    op.drop_table('s3_file_version')
    op.drop_table('s3_file')
    # ### end Alembic commands ###
