"""order data

Revision ID: 7746ef7723c9
Revises: 3944b52aa644
Create Date: 2020-04-23 08:31:21.958620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7746ef7723c9'
down_revision = '3944b52aa644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('order_version', sa.Column('data', sa.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_version', 'data')
    op.drop_column('order', 'data')
    # ### end Alembic commands ###
