"""settings table

Revision ID: 7b98d951a246
Revises: 23585e506329
Create Date: 2019-08-07 08:46:57.924863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b98d951a246'
down_revision = '23585e506329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(length=40), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('section', sa.String(length=40), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_settings_version_end_transaction_id'), 'settings_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_settings_version_operation_type'), 'settings_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_settings_version_transaction_id'), 'settings_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_settings_version_transaction_id'), table_name='settings_version')
    op.drop_index(op.f('ix_settings_version_operation_type'), table_name='settings_version')
    op.drop_index(op.f('ix_settings_version_end_transaction_id'), table_name='settings_version')
    op.drop_table('settings_version')
    op.drop_table('settings')
    # ### end Alembic commands ###
