"""user role added

Revision ID: 7ea3a804ca15
Revises: b26d194eae74
Create Date: 2019-06-04 13:19:58.531469

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ea3a804ca15'
down_revision = 'b26d194eae74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=150), nullable=False),
    sa.Column('public_id', sa.String(length=100), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('user_role_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('label', sa.String(length=150), autoincrement=False, nullable=True),
    sa.Column('public_id', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_user_role_version_end_transaction_id'), 'user_role_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_role_version_operation_type'), 'user_role_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_user_role_version_transaction_id'), 'user_role_version', ['transaction_id'], unique=False)
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_role', ['role_id'], ['id'])
    op.add_column('user_version', sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_version', 'role_id')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_index(op.f('ix_user_role_version_transaction_id'), table_name='user_role_version')
    op.drop_index(op.f('ix_user_role_version_operation_type'), table_name='user_role_version')
    op.drop_index(op.f('ix_user_role_version_end_transaction_id'), table_name='user_role_version')
    op.drop_table('user_role_version')
    op.drop_table('user_role')
    # ### end Alembic commands ###
