"""user changes

Revision ID: 7f069b7d2f1e
Revises: b81f4746c813
Create Date: 2019-06-25 10:07:15.555922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f069b7d2f1e'
down_revision = 'b81f4746c813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_role', sa.Column('code', sa.String(length=60), nullable=True))
    op.create_unique_constraint(None, 'user_role', ['code'])
    op.add_column('user_role_version', sa.Column('code', sa.String(length=60), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_role_version', 'code')
    op.drop_constraint(None, 'user_role', type_='unique')
    op.drop_column('user_role', 'code')
    # ### end Alembic commands ###
