"""empty message

Revision ID: 8828c8b20dcc
Revises: ed67ce5d0849
Create Date: 2019-12-05 16:23:21.767430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8828c8b20dcc'
down_revision = 'ed67ce5d0849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer_v2_items_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('offer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('sort', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('number', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('label', sa.String(length=200), autoincrement=False, nullable=True),
    sa.Column('description', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('data', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('calculation', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('price_definition', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('weight_single', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('weight_total', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('single_price', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('single_price_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('single_tax_amount', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_single_amount', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_single_price', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_single_price_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_single_price_net_overwrite', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_single_tax_amount', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_total_amount', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('total_price_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('total_tax_amount', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_offer_v2_items_version_end_transaction_id'), 'offer_v2_items_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_offer_v2_items_version_operation_type'), 'offer_v2_items_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_offer_v2_items_version_transaction_id'), 'offer_v2_items_version', ['transaction_id'], unique=False)
    op.create_table('offer_v2_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('payment_account_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('lead_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('survey_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('offer_group', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('currency', sa.String(length=10), autoincrement=False, nullable=True),
    sa.Column('tax_rate', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('subtotal_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('shipping_cost_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('last_updated', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_offer_v2_version_end_transaction_id'), 'offer_v2_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_offer_v2_version_operation_type'), 'offer_v2_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_offer_v2_version_transaction_id'), 'offer_v2_version', ['transaction_id'], unique=False)
    op.create_table('offer_v2',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('offer_group', sa.String(length=20), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('subtotal_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('shipping_cost_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_total', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_tax', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['lead.id'], ),
    sa.ForeignKeyConstraint(['payment_account_id'], ['customer_payment_account.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_v2_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=50), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('calculation', sa.JSON(), nullable=True),
    sa.Column('price_definition', sa.JSON(), nullable=True),
    sa.Column('weight_single', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('weight_total', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=True),
    sa.Column('single_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('single_price_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('single_tax_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_single_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_single_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_single_price_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_single_price_net_overwrite', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_single_tax_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('discount_total_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_price_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('total_tax_amount', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer_v2.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_v2_items')
    op.drop_table('offer_v2')
    op.drop_index(op.f('ix_offer_v2_version_transaction_id'), table_name='offer_v2_version')
    op.drop_index(op.f('ix_offer_v2_version_operation_type'), table_name='offer_v2_version')
    op.drop_index(op.f('ix_offer_v2_version_end_transaction_id'), table_name='offer_v2_version')
    op.drop_table('offer_v2_version')
    op.drop_index(op.f('ix_offer_v2_items_version_transaction_id'), table_name='offer_v2_items_version')
    op.drop_index(op.f('ix_offer_v2_items_version_operation_type'), table_name='offer_v2_items_version')
    op.drop_index(op.f('ix_offer_v2_items_version_end_transaction_id'), table_name='offer_v2_items_version')
    op.drop_table('offer_v2_items_version')
    # ### end Alembic commands ###
