"""action and link added to task

Revision ID: 884ffbbd4189
Revises: 9b0e4bd1031c
Create Date: 2019-07-11 13:35:03.628623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884ffbbd4189'
down_revision = '9b0e4bd1031c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('action', sa.String(length=50), nullable=True))
    op.add_column('task', sa.Column('link', sa.String(length=50), nullable=True))
    op.add_column('task_version', sa.Column('action', sa.String(length=50), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('link', sa.String(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_version', 'link')
    op.drop_column('task_version', 'action')
    op.drop_column('task', 'link')
    op.drop_column('task', 'action')
    # ### end Alembic commands ###
