"""invoice_bundles added

Revision ID: 8c6c11ff132b
Revises: 37d8b3ab7262
Create Date: 2022-08-02 08:03:20.407558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8c6c11ff132b'
down_revision = '37d8b3ab7262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_bundle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kw', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('download_datetime', sa.DateTime(), nullable=True),
    sa.Column('download_by_user_id', sa.Integer(), nullable=True),
    sa.Column('import_datetime', sa.DateTime(), nullable=True),
    sa.Column('import_by_user_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoice_bundle_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('invoice_bundle_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('invoice_number', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.ForeignKeyConstraint(['invoice_bundle_id'], ['invoice_bundle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice_bundle_item')
    op.drop_table('invoice_bundle')
    # ### end Alembic commands ###
