"""importer

Revision ID: 91e25a4a6c03
Revises: a95f5937ed34
Create Date: 2019-07-10 13:30:40.782506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91e25a4a6c03'
down_revision = 'a95f5937ed34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_id_association',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('local_id', sa.Integer(), nullable=True),
    sa.Column('remote_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_id_association_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('source', sa.String(length=40), autoincrement=False, nullable=True),
    sa.Column('model', sa.String(length=60), autoincrement=False, nullable=True),
    sa.Column('local_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('remote_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_import_id_association_version_end_transaction_id'), 'import_id_association_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_import_id_association_version_operation_type'), 'import_id_association_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_import_id_association_version_transaction_id'), 'import_id_association_version', ['transaction_id'], unique=False)
    op.add_column('contract_version', sa.Column('calculation', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('contract_version', sa.Column('data', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('contract_version', sa.Column('errors', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('contract_version', sa.Column('last_updated', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('contract_version', sa.Column('offer_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('contract_version', sa.Column('price_definition', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('contract_version', sa.Column('status', sa.String(length=20), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('name', sa.String(length=80), autoincrement=False, nullable=True))
    op.add_column('reseller_version', sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('survey_version', sa.Column('data_status', sa.String(length=30), autoincrement=False, nullable=True))
    op.add_column('survey_version', sa.Column('offer_status', sa.String(length=30), autoincrement=False, nullable=True))
    op.add_column('task_version', sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_version', 'user_id')
    op.drop_column('survey_version', 'offer_status')
    op.drop_column('survey_version', 'data_status')
    op.drop_column('reseller_version', 'user_id')
    op.drop_column('product_version', 'name')
    op.drop_column('contract_version', 'status')
    op.drop_column('contract_version', 'price_definition')
    op.drop_column('contract_version', 'offer_id')
    op.drop_column('contract_version', 'last_updated')
    op.drop_column('contract_version', 'errors')
    op.drop_column('contract_version', 'data')
    op.drop_column('contract_version', 'calculation')
    op.drop_index(op.f('ix_import_id_association_version_transaction_id'), table_name='import_id_association_version')
    op.drop_index(op.f('ix_import_id_association_version_operation_type'), table_name='import_id_association_version')
    op.drop_index(op.f('ix_import_id_association_version_end_transaction_id'), table_name='import_id_association_version')
    op.drop_table('import_id_association_version')
    op.drop_table('import_id_association')
    # ### end Alembic commands ###
