"""end date added for sherpa contracts

Revision ID: 92fa8c53242c
Revises: 382b529695a1
Create Date: 2023-01-30 15:47:18.009509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92fa8c53242c'
down_revision = '382b529695a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract2', sa.Column('end', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract2', 'end')
    # ### end Alembic commands ###
