"""contract_status

Revision ID: 92fc44a63b1d
Revises: a765ddef0729
Create Date: 2022-02-18 10:46:42.389745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92fc44a63b1d'
down_revision = 'a765ddef0729'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_status',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_number', sa.String(length=50), nullable=True),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('has_lightcloud', sa.Boolean(), nullable=True),
    sa.Column('has_cloud_number', sa.Boolean(), nullable=True),
    sa.Column('has_smartme_number', sa.Boolean(), nullable=True),
    sa.Column('has_smartme_number_values', sa.Boolean(), nullable=True),
    sa.Column('has_correct_usage', sa.String(length=80), nullable=True),
    sa.Column('has_sherpa_values', sa.Boolean(), nullable=True),
    sa.Column('has_heatcloud', sa.Boolean(), nullable=True),
    sa.Column('has_ecloud', sa.Boolean(), nullable=True),
    sa.Column('has_consumers', sa.Boolean(), nullable=True),
    sa.Column('has_emove', sa.Boolean(), nullable=True),
    sa.Column('pdf_file_id', sa.Integer(), nullable=True),
    sa.Column('pdf_file_link', sa.String(length=250), nullable=True),
    sa.Column('is_generated', sa.Boolean(), nullable=True),
    sa.Column('is_invoiced', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_status')
    # ### end Alembic commands ###
