"""commission change

Revision ID: 93009cb1c1f6
Revises: c8607936979b
Create Date: 2020-02-11 12:44:20.157299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93009cb1c1f6'
down_revision = 'c8607936979b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission', sa.Column('comment_external', sa.Text(), nullable=True))
    op.add_column('commission', sa.Column('comment_internal', sa.Text(), nullable=True))
    op.drop_column('commission', 'comment_interal')
    op.drop_column('commission', 'comment_exteral')
    op.add_column('commission_version', sa.Column('comment_external', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('commission_version', sa.Column('comment_internal', sa.Text(), autoincrement=False, nullable=True))
    op.drop_column('commission_version', 'comment_interal')
    op.drop_column('commission_version', 'comment_exteral')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_version', sa.Column('comment_exteral', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('commission_version', sa.Column('comment_interal', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('commission_version', 'comment_internal')
    op.drop_column('commission_version', 'comment_external')
    op.add_column('commission', sa.Column('comment_exteral', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('commission', sa.Column('comment_interal', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('commission', 'comment_internal')
    op.drop_column('commission', 'comment_external')
    # ### end Alembic commands ###
