"""task label

Revision ID: 938fb80e3dce
Revises: 3a0223d92d26
Create Date: 2020-03-12 13:59:04.692254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '938fb80e3dce'
down_revision = '3a0223d92d26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_version_end_transaction_id', table_name='task_version')
    op.drop_index('ix_task_version_operation_type', table_name='task_version')
    op.drop_index('ix_task_version_transaction_id', table_name='task_version')
    op.drop_table('task_version')
    op.add_column('task', sa.Column('label', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'label')
    op.create_table('task_version',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('operation_type', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('reseller_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=60), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('lat', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('lng', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('salutation', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('street', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('street_nb', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('travel_time_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('zip', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', 'transaction_id', name='task_version_pkey')
    )
    op.create_index('ix_task_version_transaction_id', 'task_version', ['transaction_id'], unique=False)
    op.create_index('ix_task_version_operation_type', 'task_version', ['operation_type'], unique=False)
    op.create_index('ix_task_version_end_transaction_id', 'task_version', ['end_transaction_id'], unique=False)
    # ### end Alembic commands ###
