"""empty message

Revision ID: 96547aa68240
Revises: 66fd4271fac1
Create Date: 2019-10-23 08:19:51.729532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96547aa68240'
down_revision = '66fd4271fac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_action', sa.Column('conditions', sa.JSON(), nullable=True))
    op.add_column('event_action_version', sa.Column('conditions', sa.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_action_version', 'conditions')
    op.drop_column('event_action', 'conditions')
    # ### end Alembic commands ###
