"""email module

Revision ID: 973e7acfbaab
Revises: 16896bb18c44
Create Date: 2019-09-05 09:26:53.586322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973e7acfbaab'
down_revision = '16896bb18c44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=250), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('from_email', sa.String(length=60), nullable=True),
    sa.Column('from_name', sa.String(length=120), nullable=True),
    sa.Column('recipients', sa.JSON(), nullable=True),
    sa.Column('cc', sa.JSON(), nullable=True),
    sa.Column('bcc', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=True),
    sa.Column('html_body', sa.TEXT(), nullable=True),
    sa.Column('text_body', sa.TEXT(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_template',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('from_email', sa.String(length=60), nullable=True),
    sa.Column('from_name', sa.String(length=120), nullable=True),
    sa.Column('cc', sa.JSON(), nullable=True),
    sa.Column('bcc', sa.JSON(), nullable=True),
    sa.Column('subject', sa.String(length=120), nullable=True),
    sa.Column('html_body', sa.TEXT(), nullable=True),
    sa.Column('text_body', sa.TEXT(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_template_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('code', sa.String(length=60), autoincrement=False, nullable=True),
    sa.Column('from_email', sa.String(length=60), autoincrement=False, nullable=True),
    sa.Column('from_name', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('cc', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('bcc', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('subject', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('html_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('text_body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attachments', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_email_template_version_end_transaction_id'), 'email_template_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_email_template_version_operation_type'), 'email_template_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_email_template_version_transaction_id'), 'email_template_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_template_version_transaction_id'), table_name='email_template_version')
    op.drop_index(op.f('ix_email_template_version_operation_type'), table_name='email_template_version')
    op.drop_index(op.f('ix_email_template_version_end_transaction_id'), table_name='email_template_version')
    op.drop_table('email_template_version')
    op.drop_table('email_template')
    op.drop_table('email')
    # ### end Alembic commands ###
