"""delivery begin added for contracts

Revision ID: 9b0e4bd1031c
Revises: 91e25a4a6c03
Create Date: 2019-07-10 15:45:59.697796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0e4bd1031c'
down_revision = '91e25a4a6c03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('delivery_begin', sa.Date(), nullable=True))
    op.add_column('contract_version', sa.Column('delivery_begin', sa.Date(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_version', 'delivery_begin')
    op.drop_column('contract', 'delivery_begin')
    # ### end Alembic commands ###
