"""order, commission changes

Revision ID: 9f54418f1d0c
Revises: 167225ff5cea
Create Date: 2020-02-11 10:00:53.172305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f54418f1d0c'
down_revision = '167225ff5cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_checked', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('is_paid', sa.Boolean(), nullable=True))
    op.add_column('order_version', sa.Column('is_checked', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('order_version', sa.Column('is_paid', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_version', 'is_paid')
    op.drop_column('order_version', 'is_checked')
    op.drop_column('order', 'is_paid')
    op.drop_column('order', 'is_checked')
    # ### end Alembic commands ###
