"""contract status

Revision ID: a1ab4838fbdb
Revises: c08f9ddb1374
Create Date: 2022-02-23 13:58:42.446942

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1ab4838fbdb'
down_revision = 'c08f9ddb1374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_status', sa.Column('has_begin_date', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_status', 'has_begin_date')
    # ### end Alembic commands ###
