"""order, commission changes

Revision ID: a1b17c672c8f
Revises: 9f54418f1d0c
Create Date: 2020-02-11 10:02:48.477930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b17c672c8f'
down_revision = '9f54418f1d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('number', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('year', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('month', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('taxrate', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('value_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('comment_interal', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('comment_exteral', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('is_checked', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('is_paid', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_commission_version_end_transaction_id'), 'commission_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_commission_version_operation_type'), 'commission_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_commission_version_transaction_id'), 'commission_version', ['transaction_id'], unique=False)
    op.create_table('commission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('taxrate', sa.Integer(), nullable=True),
    sa.Column('value_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('value', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('comment_interal', sa.Text(), nullable=True),
    sa.Column('comment_exteral', sa.Text(), nullable=True),
    sa.Column('is_checked', sa.Boolean(), nullable=True),
    sa.Column('is_paid', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commission')
    op.drop_index(op.f('ix_commission_version_transaction_id'), table_name='commission_version')
    op.drop_index(op.f('ix_commission_version_operation_type'), table_name='commission_version')
    op.drop_index(op.f('ix_commission_version_end_transaction_id'), table_name='commission_version')
    op.drop_table('commission_version')
    # ### end Alembic commands ###
