"""invoice_bundles added

Revision ID: a1e51c00bad4
Revises: 8c6c11ff132b
Create Date: 2022-08-02 08:05:50.906536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1e51c00bad4'
down_revision = '8c6c11ff132b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_bundle', sa.Column('download_link', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_bundle', 'download_link')
    # ### end Alembic commands ###
