"""user and calendar events

Revision ID: a218ae979f10
Revises: 93009cb1c1f6
Create Date: 2020-03-05 08:55:32.213059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a218ae979f10'
down_revision = '93009cb1c1f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_event_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('salutation', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('company', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('street', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('street_nb', sa.String(length=80), autoincrement=False, nullable=True),
    sa.Column('street_extra', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('zip', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('city', sa.String(length=60), autoincrement=False, nullable=True),
    sa.Column('distance_km', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('travel_time_minutes', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('lat', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('lng', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('type', sa.String(length=40), autoincrement=False, nullable=True),
    sa.Column('begin', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('end', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('comment', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_calendar_event_version_end_transaction_id'), 'calendar_event_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_calendar_event_version_operation_type'), 'calendar_event_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_calendar_event_version_transaction_id'), 'calendar_event_version', ['transaction_id'], unique=False)
    op.create_table('calendar_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('salutation', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('street_nb', sa.String(length=80), nullable=True),
    sa.Column('street_extra', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('travel_time_minutes', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=True),
    sa.Column('begin', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('bitrix_department', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('name', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    op.drop_column('user', 'bitrix_department')
    op.drop_column('user', 'active')
    op.drop_table('calendar_event')
    op.drop_index(op.f('ix_calendar_event_version_transaction_id'), table_name='calendar_event_version')
    op.drop_index(op.f('ix_calendar_event_version_operation_type'), table_name='calendar_event_version')
    op.drop_index(op.f('ix_calendar_event_version_end_transaction_id'), table_name='calendar_event_version')
    op.drop_table('calendar_event_version')
    # ### end Alembic commands ###
