"""lead last status change

Revision ID: a42441cb8e7d
Revises: 4f272d3eb7d5
Create Date: 2019-10-22 08:03:42.268274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a42441cb8e7d'
down_revision = '4f272d3eb7d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('last_status_update', sa.DateTime(), nullable=True))
    op.add_column('lead', sa.Column('reseller_billed', sa.Boolean(), nullable=True))
    op.add_column('lead_version', sa.Column('last_status_update', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('lead_version', sa.Column('reseller_billed', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_version', 'reseller_billed')
    op.drop_column('lead_version', 'last_status_update')
    op.drop_column('lead', 'reseller_billed')
    op.drop_column('lead', 'last_status_update')
    # ### end Alembic commands ###
