"""sherpa_invoices added

Revision ID: a765ddef0729
Revises: b6b69c3ac48f
Create Date: 2022-02-17 10:08:14.801054

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a765ddef0729'
down_revision = 'b6b69c3ac48f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sherpa_invoice',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identnummer', sa.String(length=50), nullable=True),
    sa.Column('rechnungsnummer', sa.String(length=60), nullable=True),
    sa.Column('abrechnungszeitraum_von', sa.DateTime(), nullable=True),
    sa.Column('abrechnungszeitraum_bis', sa.DateTime(), nullable=True),
    sa.Column('zahlernummer', sa.String(length=60), nullable=True),
    sa.Column('abrechnungsart', sa.String(length=60), nullable=True),
    sa.Column('verbrauch', sa.Integer(), nullable=True),
    sa.Column('tage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sherpa_invoice_item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sherpa_invoice_id', sa.Integer(), nullable=True),
    sa.Column('zahlernummer', sa.String(length=60), nullable=True),
    sa.Column('art_des_zahlerstandes', sa.String(length=60), nullable=True),
    sa.Column('zahlerart', sa.String(length=60), nullable=True),
    sa.Column('stand_alt', sa.Integer(), nullable=True),
    sa.Column('datum_stand_alt', sa.DateTime(), nullable=True),
    sa.Column('ablesegrund', sa.String(length=60), nullable=True),
    sa.Column('stand_neu', sa.Integer(), nullable=True),
    sa.Column('datum_stand_neu', sa.DateTime(), nullable=True),
    sa.Column('verbrauch', sa.Integer(), nullable=True),
    sa.Column('tage', sa.Integer(), nullable=True),
    sa.Column('wandlerfaktor', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['sherpa_invoice_id'], ['sherpa_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sherpa_invoice_item')
    op.drop_table('sherpa_invoice')
    # ### end Alembic commands ###
