"""sherpa original values added

Revision ID: a84cb0860a11
Revises: 3c6ce95228be
Create Date: 2022-05-19 11:26:25.134983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a84cb0860a11'
down_revision = '3c6ce95228be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('sherpa_invoice_item', sa.Column('stand_alt_sherpa', sa.Integer(), nullable=True))
    op.add_column('sherpa_invoice_item', sa.Column('stand_neu_sherpa', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sherpa_invoice_item', 'stand_neu_sherpa')
    op.drop_column('sherpa_invoice_item', 'stand_alt_sherpa')
    # ### end Alembic commands ###
