"""contract data added

Revision ID: a95f5937ed34
Revises: dd84e0d9a675
Create Date: 2019-07-09 08:30:30.787173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a95f5937ed34'
down_revision = 'dd84e0d9a675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('contract', sa.Column('calculation', sa.JSON(), nullable=True))
    op.add_column('contract', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('contract', sa.Column('errors', sa.JSON(), nullable=True))
    op.add_column('contract', sa.Column('last_updated', sa.DateTime(), nullable=True))
    op.add_column('contract', sa.Column('price_definition', sa.JSON(), nullable=True))
    op.add_column('contract', sa.Column('status', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'status')
    op.drop_column('contract', 'price_definition')
    op.drop_column('contract', 'last_updated')
    op.drop_column('contract', 'errors')
    op.drop_column('contract', 'data')
    op.drop_column('contract', 'calculation')
    # ### end Alembic commands ###
