"""task with extra color

Revision ID: a9ddd100091c
Revises: d75a2234e322
Create Date: 2020-05-27 08:00:39.824672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9ddd100091c'
down_revision = 'd75a2234e322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('color', sa.String(length=10), nullable=True))
    op.add_column('calendar_event_version', sa.Column('color', sa.String(length=10), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_version', 'color')
    op.drop_column('calendar_event', 'color')
    # ### end Alembic commands ###
