"""lead description added

Revision ID: ad5ec78193e3
Revises: fba5c74eafe8
Create Date: 2019-07-23 09:20:22.036748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5ec78193e3'
down_revision = 'fba5c74eafe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead', sa.Column('description', sa.TEXT(), nullable=True))
    op.add_column('lead', sa.Column('description_html', sa.TEXT(), nullable=True))
    op.add_column('lead_version', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('lead_version', sa.Column('description_html', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_version', 'description_html')
    op.drop_column('lead_version', 'description')
    op.drop_column('lead', 'description_html')
    op.drop_column('lead', 'description')
    # ### end Alembic commands ###
