"""eeg refund rate added

Revision ID: b3ad8ac91dd4
Revises: e67d6747e9cb
Create Date: 2020-08-24 09:21:33.148677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3ad8ac91dd4'
down_revision = 'e67d6747e9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eeg_refund_rate',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('min_kwp', sa.Float(), nullable=True),
    sa.Column('max_kwp', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eeg_refund_rate')
    # ### end Alembic commands ###
