"""new user options

Revision ID: b6b69c3ac48f
Revises: c1113823b605
Create Date: 2022-01-17 11:28:12.938790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b6b69c3ac48f'
down_revision = 'c1113823b605'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_zip_association', sa.Column('supervisor_id', sa.Integer(), nullable=True))
    op.add_column('user_zip_association', sa.Column('user_type', sa.String(length=90), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_zip_association', 'user_type')
    op.drop_column('user_zip_association', 'supervisor_id')
    # ### end Alembic commands ###
