"""user changes

Revision ID: b81f4746c813
Revises: 0ddec445f1f3
Create Date: 2019-06-25 09:51:42.793364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b81f4746c813'
down_revision = '0ddec445f1f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_public_id_key', 'customer', type_='unique')
    op.drop_column('customer', 'public_id')
    op.drop_constraint('customer_address_public_id_key', 'customer_address', type_='unique')
    op.drop_column('customer_address', 'public_id')
    op.drop_column('customer_address_version', 'public_id')
    op.drop_constraint('customer_payment_account_public_id_key', 'customer_payment_account', type_='unique')
    op.drop_column('customer_payment_account', 'public_id')
    op.drop_column('customer_payment_account_version', 'public_id')
    op.drop_column('customer_version', 'public_id')
    op.drop_column('user', 'admin')
    op.drop_constraint('user_role_public_id_key', 'user_role', type_='unique')
    op.drop_column('user_role', 'public_id')
    op.drop_column('user_role_version', 'public_id')
    op.drop_column('user_version', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_version', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user_role_version', sa.Column('public_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_role', sa.Column('public_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_unique_constraint('user_role_public_id_key', 'user_role', ['public_id'])
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('customer_version', sa.Column('public_id', sa.VARCHAR(length=38), autoincrement=False, nullable=True))
    op.add_column('customer_payment_account_version', sa.Column('public_id', sa.VARCHAR(length=38), autoincrement=False, nullable=True))
    op.add_column('customer_payment_account', sa.Column('public_id', sa.VARCHAR(length=38), autoincrement=False, nullable=True))
    op.create_unique_constraint('customer_payment_account_public_id_key', 'customer_payment_account', ['public_id'])
    op.add_column('customer_address_version', sa.Column('public_id', sa.VARCHAR(length=38), autoincrement=False, nullable=True))
    op.add_column('customer_address', sa.Column('public_id', sa.VARCHAR(length=38), autoincrement=False, nullable=True))
    op.create_unique_constraint('customer_address_public_id_key', 'customer_address', ['public_id'])
    op.add_column('customer', sa.Column('public_id', sa.VARCHAR(length=38), autoincrement=False, nullable=True))
    op.create_unique_constraint('customer_public_id_key', 'customer', ['public_id'])
    # ### end Alembic commands ###
