"""customer

Revision ID: b9065cf0a32a
Revises: 7ea3a804ca15
Create Date: 2019-06-18 09:59:31.406293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b9065cf0a32a'
down_revision = '7ea3a804ca15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=38), nullable=True),
    sa.Column('customer_number', sa.String(length=30), nullable=True),
    sa.Column('lead_number', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('salutation', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('pending_email', sa.String(length=120), nullable=True),
    sa.Column('email_status', sa.String(length=20), nullable=True),
    sa.Column('default_address_id', sa.Integer(), nullable=True),
    sa.Column('default_payment_account_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_number'),
    sa.UniqueConstraint('lead_number'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('customer_address',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=38), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('salutation', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('firstname', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('street', sa.String(length=100), nullable=True),
    sa.Column('street_nb', sa.String(length=20), nullable=True),
    sa.Column('street_extra', sa.String(length=50), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=60), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_index(op.f('ix_customer_address_customer_id'), 'customer_address', ['customer_id'], unique=False)
    op.create_table('customer_address_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.String(length=38), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('salutation', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('company', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('street', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('street_nb', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('street_extra', sa.String(length=50), autoincrement=False, nullable=True),
    sa.Column('zip', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('city', sa.String(length=60), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_customer_address_version_customer_id'), 'customer_address_version', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_address_version_end_transaction_id'), 'customer_address_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_customer_address_version_operation_type'), 'customer_address_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_customer_address_version_transaction_id'), 'customer_address_version', ['transaction_id'], unique=False)
    op.create_table('customer_payment_account',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=38), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('address_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=30), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['address_id'], ['customer_address.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    op.create_table('customer_payment_account_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.String(length=38), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('type', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_customer_payment_account_version_end_transaction_id'), 'customer_payment_account_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_customer_payment_account_version_operation_type'), 'customer_payment_account_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_customer_payment_account_version_transaction_id'), 'customer_payment_account_version', ['transaction_id'], unique=False)
    op.create_table('customer_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('public_id', sa.String(length=38), autoincrement=False, nullable=True),
    sa.Column('customer_number', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('lead_number', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('company', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('salutation', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('title', sa.String(length=30), autoincrement=False, nullable=True),
    sa.Column('firstname', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('lastname', sa.String(length=100), autoincrement=False, nullable=True),
    sa.Column('email', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('pending_email', sa.String(length=120), autoincrement=False, nullable=True),
    sa.Column('email_status', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('default_address_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('default_payment_account_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_customer_version_end_transaction_id'), 'customer_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_customer_version_operation_type'), 'customer_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_customer_version_transaction_id'), 'customer_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_version_transaction_id'), table_name='customer_version')
    op.drop_index(op.f('ix_customer_version_operation_type'), table_name='customer_version')
    op.drop_index(op.f('ix_customer_version_end_transaction_id'), table_name='customer_version')
    op.drop_table('customer_version')
    op.drop_index(op.f('ix_customer_payment_account_version_transaction_id'), table_name='customer_payment_account_version')
    op.drop_index(op.f('ix_customer_payment_account_version_operation_type'), table_name='customer_payment_account_version')
    op.drop_index(op.f('ix_customer_payment_account_version_end_transaction_id'), table_name='customer_payment_account_version')
    op.drop_table('customer_payment_account_version')
    op.drop_table('customer_payment_account')
    op.drop_index(op.f('ix_customer_address_version_transaction_id'), table_name='customer_address_version')
    op.drop_index(op.f('ix_customer_address_version_operation_type'), table_name='customer_address_version')
    op.drop_index(op.f('ix_customer_address_version_end_transaction_id'), table_name='customer_address_version')
    op.drop_index(op.f('ix_customer_address_version_customer_id'), table_name='customer_address_version')
    op.drop_table('customer_address_version')
    op.drop_index(op.f('ix_customer_address_customer_id'), table_name='customer_address')
    op.drop_table('customer_address')
    op.drop_table('customer')
    # ### end Alembic commands ###
