"""user multible roles

Revision ID: b9fd437fbf18
Revises: a0c3031a94c7
Create Date: 2019-07-02 08:49:34.528551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9fd437fbf18'
down_revision = 'a0c3031a94c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_role_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_role_id'], ['user_role.id'], )
    )
    op.create_table('user_role_association_version',
    sa.Column('user_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('user_role_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.create_index(op.f('ix_user_role_association_version_end_transaction_id'), 'user_role_association_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_user_role_association_version_operation_type'), 'user_role_association_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_user_role_association_version_transaction_id'), 'user_role_association_version', ['transaction_id'], unique=False)
    op.add_column('customer', sa.Column('last_change', sa.DateTime(), nullable=True))
    op.add_column('customer_version', sa.Column('last_change', sa.DateTime(), autoincrement=False, nullable=True))
    op.drop_constraint('user_role_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    op.drop_column('user_version', 'role_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_version', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_role_id_fkey', 'user', 'user_role', ['role_id'], ['id'])
    op.drop_column('customer_version', 'last_change')
    op.drop_column('customer', 'last_change')
    op.drop_index(op.f('ix_user_role_association_version_transaction_id'), table_name='user_role_association_version')
    op.drop_index(op.f('ix_user_role_association_version_operation_type'), table_name='user_role_association_version')
    op.drop_index(op.f('ix_user_role_association_version_end_transaction_id'), table_name='user_role_association_version')
    op.drop_table('user_role_association_version')
    op.drop_table('user_role_association')
    # ### end Alembic commands ###
