"""product extended

Revision ID: bc183f1e7455
Revises: 154eefea79a6
Create Date: 2020-03-31 10:52:58.093006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc183f1e7455'
down_revision = '154eefea79a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_v2_items', sa.Column('quantity_unit', sa.String(length=50), nullable=True))
    op.add_column('offer_v2_items_version', sa.Column('quantity_unit', sa.String(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer_v2_items_version', 'quantity_unit')
    op.drop_column('offer_v2_items', 'quantity_unit')
    # ### end Alembic commands ###
