"""mfr event

Revision ID: c1113823b605
Revises: 831af6fcca06
Create Date: 2021-07-23 11:09:46.613168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1113823b605'
down_revision = '831af6fcca06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mfr_log_event',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_request_id', sa.String(length=200), nullable=True),
    sa.Column('last_change', sa.DateTime(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('mfr_log_event')
    # ### end Alembic commands ###
