"""tasks added

Revision ID: c127d4fcd42f
Revises: f0d39900dd15
Create Date: 2019-07-02 12:13:41.274192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c127d4fcd42f'
down_revision = 'f0d39900dd15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'task', 'user_role', ['role_id'], ['id'])
    op.add_column('task_version', sa.Column('role_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_version', 'role_id')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'role_id')
    # ### end Alembic commands ###
