"""fakturia

Revision ID: c4007ed4741b
Revises: 4c768a1f9fbf
Create Date: 2022-03-02 16:39:44.202436

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4007ed4741b'
down_revision = '4c768a1f9fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_status', sa.Column('is_fakturia', sa.Boolean(), nullable=True))
    op.add_column('contract_status', sa.Column('is_fakturia_transfered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_status', 'is_fakturia_transfered')
    op.drop_column('contract_status', 'is_fakturia')
    # ### end Alembic commands ###
