"""commission change

Revision ID: c8607936979b
Revises: a1b17c672c8f
Create Date: 2020-02-11 12:41:33.907951

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8607936979b'
down_revision = 'a1b17c672c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission', sa.Column('extra_item', sa.Text(), nullable=True))
    op.add_column('commission', sa.Column('extra_value_net', sa.Numeric(precision=12, scale=4), nullable=True))
    op.drop_column('commission', 'datetime')
    op.drop_column('commission', 'value')
    op.drop_column('commission', 'value_net')
    op.add_column('commission_version', sa.Column('extra_item', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('commission_version', sa.Column('extra_value_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.drop_column('commission_version', 'datetime')
    op.drop_column('commission_version', 'value_net')
    op.drop_column('commission_version', 'value')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commission_version', sa.Column('value', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('commission_version', sa.Column('value_net', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('commission_version', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('commission_version', 'extra_value_net')
    op.drop_column('commission_version', 'extra_item')
    op.add_column('commission', sa.Column('value_net', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('commission', sa.Column('value', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('commission', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('commission', 'extra_value_net')
    op.drop_column('commission', 'extra_item')
    # ### end Alembic commands ###
