"""order contract number

Revision ID: cea2d5162afb
Revises: b3ad8ac91dd4
Create Date: 2020-08-26 10:04:18.091555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea2d5162afb'
down_revision = 'b3ad8ac91dd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('contract_number', sa.String(length=120), nullable=True))
    op.add_column('order_version', sa.Column('contract_number', sa.String(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_version', 'contract_number')
    op.drop_column('order', 'contract_number')
    # ### end Alembic commands ###
