"""end date added for sherpa contracts

Revision ID: cf0a9d22dbbb
Revises: 92fa8c53242c
Create Date: 2023-01-30 15:57:04.534648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf0a9d22dbbb'
down_revision = '92fa8c53242c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract2', sa.Column('main_contract_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract2', 'main_contract_number')
    # ### end Alembic commands ###
