"""reseller sales area

Revision ID: cf4af72bd8cb
Revises: 460590aae513
Create Date: 2020-01-14 16:04:09.791735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4af72bd8cb'
down_revision = '460590aae513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reseller', sa.Column('sales_center', sa.String(length=140), nullable=True))
    op.add_column('reseller', sa.Column('sales_lat', sa.Float(), nullable=True))
    op.add_column('reseller', sa.Column('sales_lng', sa.Float(), nullable=True))
    op.add_column('reseller', sa.Column('sales_range', sa.Integer(), nullable=True))
    op.add_column('reseller_version', sa.Column('sales_center', sa.String(length=140), autoincrement=False, nullable=True))
    op.add_column('reseller_version', sa.Column('sales_lat', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('reseller_version', sa.Column('sales_lng', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('reseller_version', sa.Column('sales_range', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reseller_version', 'sales_range')
    op.drop_column('reseller_version', 'sales_lng')
    op.drop_column('reseller_version', 'sales_lat')
    op.drop_column('reseller_version', 'sales_center')
    op.drop_column('reseller', 'sales_range')
    op.drop_column('reseller', 'sales_lng')
    op.drop_column('reseller', 'sales_lat')
    op.drop_column('reseller', 'sales_center')
    # ### end Alembic commands ###
