"""reseller ziplist

Revision ID: d2a568dc5043
Revises: 5eb7aac2777c
Create Date: 2020-06-16 08:54:07.068957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2a568dc5043'
down_revision = '5eb7aac2777c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_v2', sa.Column('calculated', sa.JSON(), nullable=True))
    op.add_column('offer_v2', sa.Column('data', sa.JSON(), nullable=True))
    op.add_column('offer_v2', sa.Column('number', sa.String(length=40), nullable=True))
    op.add_column('offer_v2_version', sa.Column('calculated', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('offer_v2_version', sa.Column('data', sa.JSON(), autoincrement=False, nullable=True))
    op.add_column('offer_v2_version', sa.Column('number', sa.String(length=40), autoincrement=False, nullable=True))
    op.add_column('reseller', sa.Column('ziplist', sa.JSON(), nullable=True))
    op.add_column('reseller_version', sa.Column('ziplist', sa.JSON(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reseller_version', 'ziplist')
    op.drop_column('reseller', 'ziplist')
    op.drop_column('offer_v2_version', 'number')
    op.drop_column('offer_v2_version', 'data')
    op.drop_column('offer_v2_version', 'calculated')
    op.drop_column('offer_v2', 'number')
    op.drop_column('offer_v2', 'data')
    op.drop_column('offer_v2', 'calculated')
    # ### end Alembic commands ###
