"""label for orders added

Revision ID: d75a2234e322
Revises: 7746ef7723c9
Create Date: 2020-05-15 15:37:54.765155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75a2234e322'
down_revision = '7746ef7723c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('label', sa.String(length=200), nullable=True))
    op.add_column('order_version', sa.Column('label', sa.String(length=200), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_version', 'label')
    op.drop_column('order', 'label')
    # ### end Alembic commands ###
