"""addes statuses for survey

Revision ID: da1926f33f28
Revises: 42902f374e11
Create Date: 2019-07-03 14:01:37.122156

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'da1926f33f28'
down_revision = '42902f374e11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('data_status', sa.String(length=30), nullable=True))
    op.add_column('survey', sa.Column('offer_status', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'offer_status')
    op.drop_column('survey', 'data_status')
    # ### end Alembic commands ###
