"""contract.data added

Revision ID: db48589a8915
Revises: 230f9e87097c
Create Date: 2022-04-20 13:35:24.440006

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'db48589a8915'
down_revision = '230f9e87097c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract2', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract2', 'data')
    # ### end Alembic commands ###
