"""contract with offer_id

Revision ID: dd84e0d9a675
Revises: e56ef64e93d9
Create Date: 2019-07-09 08:11:21.726652

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dd84e0d9a675'
down_revision = 'e56ef64e93d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('contract', sa.Column('offer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contract', 'offer', ['offer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_column('contract', 'offer_id')

    # ### end Alembic commands ###
