"""cal event extended

Revision ID: e0fc637ec6bc
Revises: c3c712937463
Create Date: 2020-03-12 15:49:39.322861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0fc637ec6bc'
down_revision = 'c3c712937463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('calendar_event', sa.Column('label', sa.String(length=250), nullable=True))
    op.add_column('calendar_event_version', sa.Column('deadline', sa.DateTime(), autoincrement=False, nullable=True))
    op.add_column('calendar_event_version', sa.Column('label', sa.String(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_version', 'label')
    op.drop_column('calendar_event_version', 'deadline')
    op.drop_column('calendar_event', 'label')
    op.drop_column('calendar_event', 'deadline')
    # ### end Alembic commands ###
