"""order extended

Revision ID: e237b3481741
Revises: 45adc391573b
Create Date: 2020-03-11 13:03:36.726634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e237b3481741'
down_revision = '45adc391573b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event', 'street_extra')
    op.drop_column('calendar_event_version', 'street_extra')
    op.add_column('order', sa.Column('city', sa.String(length=60), nullable=True))
    op.add_column('order', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('street', sa.String(length=90), nullable=True))
    op.add_column('order', sa.Column('street_nb', sa.String(length=20), nullable=True))
    op.add_column('order', sa.Column('zip', sa.String(length=20), nullable=True))
    op.add_column('order_version', sa.Column('city', sa.String(length=60), autoincrement=False, nullable=True))
    op.add_column('order_version', sa.Column('lat', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('order_version', sa.Column('lng', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('order_version', sa.Column('street', sa.String(length=90), autoincrement=False, nullable=True))
    op.add_column('order_version', sa.Column('street_nb', sa.String(length=20), autoincrement=False, nullable=True))
    op.add_column('order_version', sa.Column('zip', sa.String(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_version', 'zip')
    op.drop_column('order_version', 'street_nb')
    op.drop_column('order_version', 'street')
    op.drop_column('order_version', 'lng')
    op.drop_column('order_version', 'lat')
    op.drop_column('order_version', 'city')
    op.drop_column('order', 'zip')
    op.drop_column('order', 'street_nb')
    op.drop_column('order', 'street')
    op.drop_column('order', 'lng')
    op.drop_column('order', 'lat')
    op.drop_column('order', 'city')
    op.add_column('calendar_event_version', sa.Column('street_extra', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('calendar_event', sa.Column('street_extra', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
