"""calendar update

Revision ID: e2b58d7a182f
Revises: a218ae979f10
Create Date: 2020-03-05 09:49:01.622326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b58d7a182f'
down_revision = 'a218ae979f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_event', sa.Column('order_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_event', 'order', ['order_id'], ['id'])
    op.add_column('calendar_event_version', sa.Column('order_id', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_event_version', 'order_id')
    op.drop_constraint(None, 'calendar_event', type_='foreignkey')
    op.drop_column('calendar_event', 'order_id')
    # ### end Alembic commands ###
