"""order added

Revision ID: e4d9b07e45ff
Revises: 23a94198b9bf
Create Date: 2020-01-27 14:41:47.370605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4d9b07e45ff'
down_revision = '23a94198b9bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('lead_number', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('reseller_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('value_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('last_update', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('contact_source', sa.String(length=80), autoincrement=False, nullable=True),
    sa.Column('status', sa.String(length=20), autoincrement=False, nullable=True),
    sa.Column('commissions', sa.JSON(), autoincrement=False, nullable=True),
    sa.Column('commission_value_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_order_version_end_transaction_id'), 'order_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_order_version_operation_type'), 'order_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_order_version_transaction_id'), 'order_version', ['transaction_id'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('lead_number', sa.String(length=20), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('reseller_id', sa.Integer(), nullable=True),
    sa.Column('value_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('contact_source', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('commissions', sa.JSON(), nullable=True),
    sa.Column('commission_value_net', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['reseller_id'], ['reseller.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_index(op.f('ix_order_version_transaction_id'), table_name='order_version')
    op.drop_index(op.f('ix_order_version_operation_type'), table_name='order_version')
    op.drop_index(op.f('ix_order_version_end_transaction_id'), table_name='order_version')
    op.drop_table('order_version')
    # ### end Alembic commands ###
