"""reseller document style

Revision ID: e60af25c82e5
Revises: d2a568dc5043
Create Date: 2020-06-29 09:21:28.145313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60af25c82e5'
down_revision = 'd2a568dc5043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reseller', sa.Column('document_style', sa.String(length=80), nullable=True))
    op.add_column('reseller_version', sa.Column('document_style', sa.String(length=80), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reseller_version', 'document_style')
    op.drop_column('reseller', 'document_style')
    # ### end Alembic commands ###
