"""offer is_sent column added

Revision ID: e67d6747e9cb
Revises: 114a3d17f550
Create Date: 2020-08-18 10:00:34.306232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67d6747e9cb'
down_revision = '114a3d17f550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer_v2', sa.Column('is_sent', sa.Boolean(), nullable=True))
    op.add_column('offer_v2_version', sa.Column('is_sent', sa.Boolean(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer_v2_version', 'is_sent')
    op.drop_column('offer_v2', 'is_sent')
    # ### end Alembic commands ###
