"""contract_status

Revision ID: ed2bd55b7afb
Revises: 0de7701bfb10
Create Date: 2022-02-24 09:09:52.813888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ed2bd55b7afb'
down_revision = '0de7701bfb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract_status', sa.Column('manuell_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract_status', 'manuell_data')
    # ### end Alembic commands ###
