"""empty message

Revision ID: ed67ce5d0849
Revises: 0bdf556fba4a
Create Date: 2019-10-23 11:45:25.143552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed67ce5d0849'
down_revision = '0bdf556fba4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reseller', sa.Column('lead_balance', sa.Integer(), nullable=True))
    op.add_column('reseller_version', sa.Column('lead_balance', sa.Integer(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reseller_version', 'lead_balance')
    op.drop_column('reseller', 'lead_balance')
    # ### end Alembic commands ###
