"""invoice_bundles added

Revision ID: edea5a21b255
Revises: a1e51c00bad4
Create Date: 2022-08-02 08:45:22.185802

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'edea5a21b255'
down_revision = 'a1e51c00bad4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_bundle', sa.Column('items_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_bundle', 'items_count')
    # ### end Alembic commands ###
