"""tasks added

Revision ID: f0d39900dd15
Revises: b9fd437fbf18
Create Date: 2019-07-02 12:10:42.597993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0d39900dd15'
down_revision = 'b9fd437fbf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('reminder_datetime', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('reminder_datetime', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('description', sa.String(length=255), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_task_version_end_transaction_id'), 'task_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_task_version_operation_type'), 'task_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_task_version_transaction_id'), 'task_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_version_transaction_id'), table_name='task_version')
    op.drop_index(op.f('ix_task_version_operation_type'), table_name='task_version')
    op.drop_index(op.f('ix_task_version_end_transaction_id'), table_name='task_version')
    op.drop_table('task_version')
    op.drop_table('task')
    # ### end Alembic commands ###
