"""deal_id for contracts added

Revision ID: f48a01a6e7cc
Revises: cf0a9d22dbbb
Create Date: 2023-02-07 08:38:49.065785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f48a01a6e7cc'
down_revision = 'cf0a9d22dbbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract2', sa.Column('deal_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract2', 'deal_id')
    # ### end Alembic commands ###
