"""empty message

Revision ID: f49f71d929a0
Revises: 8828c8b20dcc
Create Date: 2019-12-06 08:59:49.202802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f49f71d929a0'
down_revision = '8828c8b20dcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('product', sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('discount_percent', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('ean', sa.String(length=120), nullable=True))
    op.add_column('product', sa.Column('height', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('length', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('min_purchase', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('pack_unit', sa.String(length=40), nullable=True))
    op.add_column('product', sa.Column('price_net', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('product_group', sa.String(length=80), nullable=True))
    op.add_column('product', sa.Column('purchase_unit', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('reference_unit', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('shipping_time', sa.String(length=60), nullable=True))
    op.add_column('product', sa.Column('tax_rate', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('tollnumber', sa.String(length=80), nullable=True))
    op.add_column('product', sa.Column('weight', sa.Numeric(precision=12, scale=4), nullable=True))
    op.add_column('product', sa.Column('width', sa.Numeric(precision=12, scale=4), nullable=True))
    op.drop_column('product', 'type')
    op.add_column('product_version', sa.Column('active', sa.Boolean(), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('cost', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('discount_percent', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('ean', sa.String(length=120), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('height', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('length', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('min_purchase', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('pack_unit', sa.String(length=40), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('price_net', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('product_group', sa.String(length=80), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('purchase_unit', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('reference_unit', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('shipping_time', sa.String(length=60), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('tax_rate', sa.Integer(), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('tollnumber', sa.String(length=80), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('weight', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.add_column('product_version', sa.Column('width', sa.Numeric(precision=12, scale=4), autoincrement=False, nullable=True))
    op.drop_column('product_version', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_version', sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('product_version', 'width')
    op.drop_column('product_version', 'weight')
    op.drop_column('product_version', 'tollnumber')
    op.drop_column('product_version', 'tax_rate')
    op.drop_column('product_version', 'shipping_time')
    op.drop_column('product_version', 'reference_unit')
    op.drop_column('product_version', 'purchase_unit')
    op.drop_column('product_version', 'product_group')
    op.drop_column('product_version', 'price_net')
    op.drop_column('product_version', 'pack_unit')
    op.drop_column('product_version', 'min_purchase')
    op.drop_column('product_version', 'length')
    op.drop_column('product_version', 'height')
    op.drop_column('product_version', 'ean')
    op.drop_column('product_version', 'discount_percent')
    op.drop_column('product_version', 'cost')
    op.drop_column('product_version', 'active')
    op.add_column('product', sa.Column('type', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_column('product', 'width')
    op.drop_column('product', 'weight')
    op.drop_column('product', 'tollnumber')
    op.drop_column('product', 'tax_rate')
    op.drop_column('product', 'shipping_time')
    op.drop_column('product', 'reference_unit')
    op.drop_column('product', 'purchase_unit')
    op.drop_column('product', 'product_group')
    op.drop_column('product', 'price_net')
    op.drop_column('product', 'pack_unit')
    op.drop_column('product', 'min_purchase')
    op.drop_column('product', 'length')
    op.drop_column('product', 'height')
    op.drop_column('product', 'ean')
    op.drop_column('product', 'discount_percent')
    op.drop_column('product', 'cost')
    op.drop_column('product', 'active')
    # ### end Alembic commands ###
