"""enbw contracts

Revision ID: f8c8e0f7b590
Revises: f04240691f70
Create Date: 2023-01-23 09:59:02.698059

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alaembic.
revision = 'f8c8e0f7b590'
down_revision = 'f04240691f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enbw_contract',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_contract_number', sa.String(length=120), nullable=True),
    sa.Column('sub_contract_number', sa.String(length=120), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('joulesId', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enbw_contract_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enbw_contract_id', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=True),
    sa.Column('post_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_response_status', sa.String(length=20), nullable=True),
    sa.Column('api_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_response_raw', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['enbw_contract_id'], ['enbw_contract.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enbw_contract_history')
    op.drop_table('enbw_contract')
    # ### end Alembic commands ###
