"""task link as text

Revision ID: fba5c74eafe8
Revises: 75ca5295cbb0
Create Date: 2019-07-19 11:46:34.868334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fba5c74eafe8'
down_revision = '75ca5295cbb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_address_customer_id', table_name='customer_address')
    op.drop_index('ix_customer_address_version_customer_id', table_name='customer_address_version')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_customer_address_version_customer_id', 'customer_address_version', ['customer_id'], unique=False)
    op.create_index('ix_customer_address_customer_id', 'customer_address', ['customer_id'], unique=False)
    # ### end Alembic commands ###
