"""bundle is_complete

Revision ID: ff7b2a6133b3
Revises: 9e4328c625f8
Create Date: 2022-08-05 09:38:57.514862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff7b2a6133b3'
down_revision = '9e4328c625f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_bundle', sa.Column('is_complete', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_bundle', 'is_complete')
    # ### end Alembic commands ###
